# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0005_testdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdata',
            name='id',
        ),
        migrations.AddField(
            model_name='testdata',
            name='Id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
