# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0007_auto_20180615_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
