# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0008_delete_billing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testdata',
        ),
    ]
