# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0010_auto_20180620_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='userad',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/users/'),
        ),
    ]
