# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-22 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0012_userad_uploaded_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userad',
            old_name='user_id',
            new_name='postid',
        ),
    ]
