# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0013_auto_20180622_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replyad',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='media/users/')),
                ('uploaded_file_url', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userad',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
