# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-24 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0014_auto_20180623_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userad',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
