# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0016_europeads_usads'),
    ]

    operations = [
        migrations.AddField(
            model_name='europeads',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
