# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-05 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0017_europeads_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitfeedback',
            fields=[
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
