# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-08 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plentyofcats', '0018_submitfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyad',
            name='uploaded_file_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usads',
            name='uploaded_file_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userad',
            name='uploaded_file_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
